### ISSUE TITLE
How many calls to `data-sortable-update-url` should occur when an item is moved?

### ISSUE THREAD

**Issue by kcdragon** [stimulus-components/stimulus-sortable#13]
Hi. This is more of a question than an issue. Apologies if this is not the right place to ask but I wasn't sure where else to go.

If I have a list of items (in my case my list is a `tbody` and my rows are `tr`) with positions of 1, 2 and 3 and I move the second item to the first item in the list, this produces a single request to `data-sortable-update-url` which changes the second item's position to 1. This leaves me in a state where the positions are 1, 1 and 3 which means I'm in a state where the ordering is unpredictable.

My expectation would be that I get an additional request for the first item (changing it to position 2) but this is not happening. Am I misunderstanding how this component works or is there a bug in my code and I should be getting two requests?

Thanks for your help.

**Comment by ManuelFrigerio** [comment]
I have the exact same question.

When an element's position changes ALL element's position do.

**Comment by guillaumebriday** [comment]
This should be handle on the backend side.

For instance, this is exactly what https://github.com/brendon/acts_as_list does. 

If you move an item from position 5 to 2, all other item will be updated.

With a query that looks like this:
```SQL
 UPDATE "posts" SET "posts"."position" = "posts"."position" + 1 WHERE "posts"."position" > 2 
```

So only one call should occur when updating an item position 👍
