### ISSUE TITLE
Use this repository without Rails

### ISSUE THREAD

**Issue by seb-jean** [stimulus-components/stimulus-sortable#15]
Hello,

Can we use this repository without using Rails? Because this repository uses Rails Request.JS.
I use Symfony.
Thanks

**Comment by guillaumebriday** [comment]
Hey @seb-jean 

This package is back-end independent, you can use it with whatever you want 👍 

`@rails/request.js` is only used here to make the ajax request with ease and to handle CSRF token.

If needed, you can override the `end` method as well

**Comment by seb-jean** [comment]
Thanks 👍🏻
