### ISSUE TITLE
Option to replace PATCH method by a other one

### ISSUE THREAD

**Issue by seb-jean** [stimulus-components/stimulus-sortable#22]
Hi,

I take back ticket #7. I have the same problem.
I arrive well with a `POST` method but not with a `PATCH` method. I'm on Symfony. Symfony does not include parameters when it is `PATCH`.

It might then be interesting to add a `data-sortable-update-method` attribute with a default value to `PATCH`

**Comment by guillaumebriday** [comment]
Hum, do you know why Symfony ignores the params when it's a `PATCH`?

But yep that could be a new option for sure, interesting in opening a PR for that?

**Comment by seb-jean** [comment]
No, I don't know why.

It might be interesting to open a PR for that.

**Comment by guillaumebriday** [comment]
Hum weird, because also on Symfony you don't want to update a resource with a POST right?

So I think it's more a problem on Symfony (or your specific project) than this lib 

Closing for now, if you think I'm wrong feel free to reopen

**Comment by seb-jean** [comment]
For Symfony, it's linked with this discussion https://github.com/symfony/symfony/pull/10381
