### ISSUE TITLE
`@rails/request.js` is a dependency

### ISSUE THREAD

**Issue by ghiculescu** [stimulus-components/stimulus-sortable#24]
I'm not sure how to update the docs, but https://www.stimulus-components.com/docs/stimulus-sortable/ lists this install command:

```
yarn add stimulus-sortable sortablejs
```

In reality it should be:

```
yarn add stimulus-sortable sortablejs @rails/request.js
```

Because of this line: https://github.com/stimulus-components/stimulus-sortable/blob/1d8d36b72fc74e87755316a1183a2a645475d030/src/index.ts#L3 and this line: https://github.com/stimulus-components/stimulus-sortable/blob/1d8d36b72fc74e87755316a1183a2a645475d030/package.json#L40

**Comment by trsteel88** [comment]
Had the same problem. Thanks @ghiculescu

**Comment by guillaumebriday** [comment]
Fixed here https://github.com/stimulus-components/stimulus-components/commit/a80d69a7bf46c68172c685f85fd84c6726e0ab71

Thanks for noticing
