### ISSUE TITLE
Option to replace patch method by a other one

### ISSUE THREAD

**Issue by jfsenechal** [stimulus-components/stimulus-sortable#7]
Hi

It would be cool if we could replace the method

 It's difficult to retrieve a value sent by patch than by post or get

Thank you

**Comment by guillaumebriday** [comment]
Which method?

Are you talking about this http verb in the Rails UJS request here https://github.com/stimulus-components/stimulus-sortable/blob/master/src/index.js#L41?

**Comment by jfsenechal** [comment]
Yes

**Comment by guillaumebriday** [comment]
Why would you want to update something with a different verb then `PATCH`?

**Comment by jfsenechal** [comment]
Because, the result is not idempotent and is difficult to catch

**Comment by guillaumebriday** [comment]
I don't get it, 

For now, you can override the [end](https://github.com/stimulus-components/stimulus-sortable/blob/master/src/index.js#L29) method, it should work for you 👍
